[package]
name = "arctis7-batteryreader-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hidapi = "2.6.1"
image = "0.25.0"
tray-icon = "0.12.0"
winit = "0.29.15"
